# TCL File Generated by Component Editor 14.0
# Fri Sep 28 17:31:22 MSD 2018
# DO NOT MODIFY


# 
# ow_protocol "1-Wire Protocol" v1.0
#  2018.09.28.17:31:22
# 
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module ow_protocol
# 
set_module_property DESCRIPTION ""
set_module_property NAME ow_protocol
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Protocol
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "1-Wire Protocol"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ow_protocol
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ow_protocol.sv SYSTEM_VERILOG PATH ow_protocol.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point ow_protocol
# 
add_interface ow_protocol conduit end
set_interface_property ow_protocol associatedClock clock
set_interface_property ow_protocol associatedReset reset
set_interface_property ow_protocol ENABLED true
set_interface_property ow_protocol EXPORT_OF ""
set_interface_property ow_protocol PORT_NAME_MAP ""
set_interface_property ow_protocol CMSIS_SVD_VARIABLES ""
set_interface_property ow_protocol SVD_ADDRESS_GROUP ""

add_interface_port ow_protocol error error Output 1
add_interface_port ow_protocol ready ready Output 1
add_interface_port ow_protocol rdreq rdreq Output 1
add_interface_port ow_protocol rdready rdready Input 1
add_interface_port ow_protocol wrreq wrreq Output 1
add_interface_port ow_protocol wrready wrready Input 1


# 
# connection point slave
# 
add_interface slave conduit end
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset reset
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave slave_ctrl ctrl Output 1
add_interface_port slave slave_error error Input 1
add_interface_port slave slave_ready ready Input 1


# 
# connection point owire
# 
add_interface owire conduit end
set_interface_property owire associatedClock clock
set_interface_property owire associatedReset reset
set_interface_property owire ENABLED true
set_interface_property owire EXPORT_OF ""
set_interface_property owire PORT_NAME_MAP ""
set_interface_property owire CMSIS_SVD_VARIABLES ""
set_interface_property owire SVD_ADDRESS_GROUP ""

add_interface_port owire ow_cmd cmd Output 3
add_interface_port owire ow_presence presence Input 1
add_interface_port owire ow_error error Input 1
add_interface_port owire ow_done done Input 1
add_interface_port owire ow_irq irq Input 1
add_interface_port owire clear clear Input 1


# 
# connection point data_bus
# 
add_interface data_bus conduit end
set_interface_property data_bus associatedClock clock
set_interface_property data_bus associatedReset reset
set_interface_property data_bus ENABLED true
set_interface_property data_bus EXPORT_OF ""
set_interface_property data_bus PORT_NAME_MAP ""
set_interface_property data_bus CMSIS_SVD_VARIABLES ""
set_interface_property data_bus SVD_ADDRESS_GROUP ""

add_interface_port data_bus bus_in in Input 8
add_interface_port data_bus data_in out Input 8


# 
# connection point crc
# 
add_interface crc conduit end
set_interface_property crc associatedClock clock
set_interface_property crc associatedReset reset
set_interface_property crc ENABLED true
set_interface_property crc EXPORT_OF ""
set_interface_property crc PORT_NAME_MAP ""
set_interface_property crc CMSIS_SVD_VARIABLES ""
set_interface_property crc SVD_ADDRESS_GROUP ""

add_interface_port crc crc_valid valid Input 1
add_interface_port crc crc8_enable enable8 Output 1
add_interface_port crc crc16_enable enable16 Output 1


# 
# connection point family
# 
add_interface family conduit end
set_interface_property family associatedClock clock
set_interface_property family associatedReset reset
set_interface_property family ENABLED true
set_interface_property family EXPORT_OF ""
set_interface_property family PORT_NAME_MAP ""
set_interface_property family CMSIS_SVD_VARIABLES ""
set_interface_property family SVD_ADDRESS_GROUP ""

add_interface_port family family device Output 8

